In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/tcs_stock_data_eda.csv")

df["Date"] = pd.to_datetime(df["Date"])
df = df.set_index("Date")

df.head()

,Open,High,Low,Close,Volume,MA20,MA50,Daily_Return,Volatility
Date,,,,,,,,,
2018-01-01,1341.150024,1347.400024,1317.500000,1322.800049,1351760,NaN,NaN,NaN,NaN
2018-01-02,1330.000000,1334.800049,1310.099976,1315.599976,1920290,NaN,NaN,-0.005443,NaN
2018-01-03,1316.000000,1334.500000,1315.599976,1319.324951,1257120,NaN,NaN,0.002831,NaN
2018-01-04,1325.000000,1331.000000,1320.000000,1328.550049,913082,NaN,NaN,0.006992,NaN
2018-01-05,1325.000000,1349.750000,1325.000000,1344.599976,1153706,NaN,NaN,0.012081,NaN

In [3]:
df["lag_1"] = df["Close"].shift(1)
df["lag_2"] = df["Close"].shift(2)
df["lag_3"] = df["Close"].shift(3)
df["lag_5"] = df["Close"].shift(5)
df["lag_10"] = df["Close"].shift(10)

In [4]:
df["rolling_mean_5"] = df["Close"].rolling(window=5).mean()
df["rolling_mean_10"] = df["Close"].rolling(window=10).mean()

df["rolling_std_5"] = df["Close"].rolling(window=5).std()
df["rolling_std_10"] = df["Close"].rolling(window=10).std()

In [5]:
df["momentum"] = df["Close"] - df["Close"].shift(5)

In [6]:
df["price_change"] = df["Close"] - df["Open"]

In [7]:
df["target"] = df["Close"].shift(-5)

In [8]:
df = df.dropna()

In [12]:
features = [
    "Open",
    "High",
    "Low",
    "Close",
    "Volume",
    "MA20",
    "MA50",
    "Daily_Return",
    "Volatility",
    "lag_1",
    "lag_2",
    "lag_3",
    "lag_5",
    "lag_10",
    "rolling_mean_5",
    "rolling_mean_10",
    "rolling_std_5",
    "rolling_std_10",
    "momentum",
    "price_change"
]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1921 entries, 2018-03-14 to 2025-12-22
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Open             1921 non-null   float64
 1   High             1921 non-null   float64
 2   Low              1921 non-null   float64
 3   Close            1921 non-null   float64
 4   Volume           1921 non-null   int64
 5   MA20             1921 non-null   float64
 6   MA50             1921 non-null   float64
 7   Daily_Return     1921 non-null   float64
 8   Volatility       1921 non-null   float64
 9   lag_1            1921 non-null   float64
 10  lag_2            1921 non-null   float64
 11  lag_3            1921 non-null   float64
 12  lag_5            1921 non-null   float64
 13  lag_10           1921 non-null   float64
 14  rolling_mean_5   1921 non-null   float64
 15  rolling_mean_10  1921 non-null   float64
 16  rolling_std_5    1921 non-null   float64
 17  rolling_std_10   1921 non-null   float64
 18  momentum         1921 non-null   float64
 19  price_change     1921 non-null   float64
 20  target           1921 non-null   float64
dtypes: float64(20), int64(1)
memory usage: 330.2 KB

In [14]:
df.to_csv("../data/processed/tcs_stock_features.csv")

In [15]:
print(df.shape)
df.head()
df.tail()

(1921, 21)

,Open,High,Low,Close,Volume,MA20,MA50,Daily_Return,Volatility,lag_1,...,lag_3,lag_5,lag_10,rolling_mean_5,rolling_mean_10,rolling_std_5,rolling_std_10,momentum,price_change,target
Date,,,,,,,,,,,,,,,,,,,,,
2025-12-16,3220.0,3220.000000,3191.100098,3205.100098,1734623,3176.934985,3091.097983,-0.007770,0.008433,3230.199951,...,3191.899902,3208.300049,3135.699951,3207.379980,3212.909985,17.806109,21.047269,-3.199951,-14.899902,3310.000000
2025-12-17,3200.5,3236.899902,3200.500000,3217.800049,1376350,3180.439990,3095.685986,0.003962,0.007359,3205.100098,...,3220.500000,3189.199951,3180.000000,3213.100000,3216.689990,14.855145,17.590556,28.600098,17.300049,3319.000000
2025-12-18,3228.0,3287.800049,3221.000000,3280.800049,2307422,3187.239990,3101.827988,0.019579,0.008411,3217.800049,...,3230.199951,3191.899902,3229.199951,3230.880029,3221.850000,29.308304,26.816646,88.900146,52.800049,3280.000000
2025-12-19,3299.0,3317.899902,3278.800049,3282.000000,3902511,3193.809985,3106.923989,0.000366,0.008421,3280.800049,...,3205.100098,3220.500000,3238.199951,3243.180029,3226.230005,36.003344,32.712637,61.500000,-17.000000,3251.500000
2025-12-22,3310.0,3328.600098,3291.000000,3324.899902,2632816,3202.994983,3112.187988,0.013071,0.008674,3282.000000,...,3217.800049,3230.199951,3236.500000,3262.120020,3235.069995,49.751890,45.313563,94.699951,14.899902,3246.800049